### ISSUE TITLE
[JENKINS-61261] Ivy ClassNotFoundException when using Grab

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-21#31]
<p>We are getting the below exception when we try to initialize and configure Jenkins plugins through post build Groovy Script under init.groovy.d. We understood this is the issue with classloader not able to find ivy in its path. However, this is working with 2.176.2 and started breaking from 2.176.3.</p>

<p> <br/>
 <br/>
@​Grab('org.yaml:snakeyaml:1.17')<br/>
import java.util.logging.Logger<br/>
import org.codehaus.groovy.control.CompilerConfiguration<br/>
import org.yaml.snakeyaml.Yaml<br/>
....<br/>
 <br/>
 <br/>
java.lang.ClassNotFoundException: org.apache.ivy.core.settings.IvySettings at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) Caused: java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings<br/>
 <br/>
 <br/>
 <br/>
We performed various work around to resolve this and none of them were successful<br/>
 <br/>
Job-DSL or Event Listener plugin cannot used since this is a config script which execute before Jenkins plugin installation/configuration. Similarly none of the pipeline utilities steps can be used at this point.<br/>
 <br/>
Cannot copy Ivy.jar to $Jenkins_Home/war/WEB_INF/lib due to the fact we run Jenkins as a docker container and war path will be only exposed after docker run which eventually invokes init.groovy.d script.<br/>
 <br/>
Tried adding the jar through classloader.<br/>
 <br/>
 </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gowthamsig">gowthamsig</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261" target="_blank">Ivy ClassNotFoundException when using Grab</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: classpath, groovy, ivy, jenkins
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2020-03-10T13:42:33+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-22
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>We are getting the below exception when we try to initialize and configure Jenkins plugins through post build Groovy Script under init.groovy.d. We understood this is the issue with classloader not able to find ivy in its path. However, this is working with 2.176.2 and started breaking from 2.176.3.</p>

<p> 
 
@Grab('org.yaml:snakeyaml:1.17')
import java.util.logging.Logger
import org.codehaus.groovy.control.CompilerConfiguration
import org.yaml.snakeyaml.Yaml
....
 
 
java.lang.ClassNotFoundException: org.apache.ivy.core.settings.IvySettings at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) Caused: java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings
 
 
 
We performed various work around to resolve this and none of them were successful
 
Job-DSL or Event Listener plugin cannot used since this is a config script which execute before Jenkins plugin installation/configuration. Similarly none of the pipeline utilities steps can be used at this point.
 
Cannot copy Ivy.jar to $Jenkins_Home/war/WEB_INF/lib due to the fact we run Jenkins as a docker container and war path will be only exposed after docker run which eventually invokes init.groovy.d script.
 
Tried adding the jar through classloader.
 
 </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins LTS docker</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/dheid.png" title="dheid's avatar" /> dheid:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261?focusedId=386105&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386105">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I don't think that this has anything to do with the postbuildscript plugin.</p>
</pre>
</details>

</ul>
</details>

<p>I don't think that this has anything to do with the postbuildscript plugin.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261?focusedId=386188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386188">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Unlikely to be a core change given <a href="https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3</a></p>

<p>My best guess is init.groovy scripts see all plugins' classes and their dependencies, and you updated a plugin at the same time that used to have Ivy on the classpath, and now don't.</p>

<p>See <a href="https://github.com/jenkinsci/jenkins/pull/2374" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/2374</a> for a PR that never got merged, and recent comments indicating plugins that include Ivy.</p>
</pre>
</details>

</ul>
</details>

<p>Unlikely to be a core change given <a href="https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3</a></p>

<p>My best guess is init.groovy scripts see all plugins' classes and their dependencies, and you updated a plugin at the same time that used to have Ivy on the classpath, and now don't.</p>

<p>See <a href="https://github.com/jenkinsci/jenkins/pull/2374" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/2374</a> for a PR that never got merged, and recent comments indicating plugins that include Ivy.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>gowthamsig:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261?focusedId=386431&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386431">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>We stood up 2.176.2 Jenkins with similar plugins (latest version) without any problem. Not sure, if this is a plugin issue.</p>

<p>As per your comment, init.groovy should find all plugin classes and their dependencies. So we also tried installing it with workflow-cps-global-lib as mentioned in the pull request mentioned as a work around. However, when the docker container is getting initialized we can see the below logs where it says started all plugins and fails to find ivy eventually</p>

<p> </p>

<p>Running from: /usr/share/jenkins/jenkins.war</p>

<p>webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")</p>

<p>Mar 03, 2020 1:50:38 PM org.eclipse.jetty.util.log.Log initialized</p>

<p>INFO: Logging initialized @673ms to org.eclipse.jetty.util.log.JavaUtilLog</p>

<p>Mar 03, 2020 1:50:38 PM winstone.Logger logInternal</p>

<p>INFO: Beginning extraction from war file</p>

<p>Mar 03, 2020 1:50:39 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath</p>

<p>WARNING: Empty contextPath</p>

<p>Mar 03, 2020 1:50:39 PM org.eclipse.jetty.server.Server doStart</p>

<p>INFO: jetty-9.4.z-SNAPSHOT; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 1.8.0_222-b10</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet</p>

<p>INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart</p>

<p>INFO: DefaultSessionIdManager workerName=node0</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart</p>

<p>INFO: No SessionScavenger set, using defaults</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging</p>

<p>INFO: node0 Scavenging every 660000ms</p>

<p>Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.handler.ContextHandler doStart</p>

<p>INFO: Started w.@66971f6b{Jenkins v2.176.3,/,<a href="file:///var/jenkins_home/war/,AVAILABLE" class="external-link" target="_blank" rel="nofollow noopener">file:///var/jenkins_home/war/,AVAILABLE</a>}</p>
{/var/jenkins_home/war}

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.AbstractConnector doStart</p>

<p>INFO: Started ServerConnector@53499d85{HTTP/1.1,<span class="error">&#91;http/1.1&#93;</span>}</p>
{0.0.0.0:8080}

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.Server doStart</p>

<p>INFO: Started @3387ms</p>

<p>Mar 03, 2020 1:50:40 PM winstone.Logger logInternal</p>

<p>INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled</p>

<p>Mar 03, 2020 1:50:43 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Started initialization</p>

<p>Mar 03, 2020 1:50:43 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Listed all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Prepared all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Started all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Augmented all extensions</p>

<p>Mar 03, 2020 1:50:46 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Loaded all jobs</p>

<p>Mar 03, 2020 1:50:46 PM hudson.model.AsyncPeriodicWork$1 run</p>

<p>INFO: Started Download metadata</p>

<p>Mar 03, 2020 1:50:46 PM hudson.util.Retrier start</p>

<p>INFO: Attempt #1 to do the action check updates server</p>

<p>Mar 03, 2020 1:50:47 PM jenkins.util.groovy.GroovyHookScript execute</p>

<p>INFO: Executing /var/jenkins_home/init.groovy.d/run.groovy</p>

<p>Mar 03, 2020 1:50:47 PM jenkins.model.Jenkins$5 runTask</p>

<p>WARNING: GroovyInitScript.init failed perhaps due to plugin dependency issues</p>

<p>java.lang.Error: java.lang.reflect.InvocationTargetException</p>

<p> at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)</p>

<p> at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)</p>

<p> at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)</p>

<p> at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)</p>

<p> at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)</p>

<p> at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)</p>

<p> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</p>

<p> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</p>

<p> at java.lang.Thread.run(Thread.java:748)</p>

<p>Caused by: java.lang.reflect.InvocationTargetException</p>

<p> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)</p>

<p> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)</p>

<p> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)</p>

<p> at java.lang.reflect.Method.invoke(Method.java:498)</p>

<p> at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)</p>

<p> ... 8 more</p>
</pre>
</details>

</ul>
</details>

<p>We stood up 2.176.2 Jenkins with similar plugins (latest version) without any problem. Not sure, if this is a plugin issue.</p>

<p>As per your comment, init.groovy should find all plugin classes and their dependencies. So we also tried installing it with workflow-cps-global-lib as mentioned in the pull request mentioned as a work around. However, when the docker container is getting initialized we can see the below logs where it says started all plugins and fails to find ivy eventually</p>

<p> </p>

<p>Running from: /usr/share/jenkins/jenkins.war</p>

<p>webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")</p>

<p>Mar 03, 2020 1:50:38 PM org.eclipse.jetty.util.log.Log initialized</p>

<p>INFO: Logging initialized @​673ms to org.eclipse.jetty.util.log.JavaUtilLog</p>

<p>Mar 03, 2020 1:50:38 PM winstone.Logger logInternal</p>

<p>INFO: Beginning extraction from war file</p>

<p>Mar 03, 2020 1:50:39 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath</p>

<p>WARNING: Empty contextPath</p>

<p>Mar 03, 2020 1:50:39 PM org.eclipse.jetty.server.Server doStart</p>

<p>INFO: jetty-9.4.z-SNAPSHOT; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 1.8.0_222-b10</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet</p>

<p>INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart</p>

<p>INFO: DefaultSessionIdManager workerName=node0</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart</p>

<p>INFO: No SessionScavenger set, using defaults</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging</p>

<p>INFO: node0 Scavenging every 660000ms</p>

<p>Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")</p>

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.handler.ContextHandler doStart</p>

<p>INFO: Started w.@​66971f6b{Jenkins v2.176.3,/,<a href="file:///var/jenkins_home/war/,AVAILABLE" class="external-link" target="_blank" rel="nofollow noopener">file:///var/jenkins_home/war/,AVAILABLE</a>}</p>
{/var/jenkins_home/war}

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.AbstractConnector doStart</p>

<p>INFO: Started ServerConnector@​53499d85{HTTP/1.1,<span class="error">&#91;http/1.1&#93;</span>}</p>
{0.0.0.0:8080}

<p>Mar 03, 2020 1:50:40 PM org.eclipse.jetty.server.Server doStart</p>

<p>INFO: Started @​3387ms</p>

<p>Mar 03, 2020 1:50:40 PM winstone.Logger logInternal</p>

<p>INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled</p>

<p>Mar 03, 2020 1:50:43 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Started initialization</p>

<p>Mar 03, 2020 1:50:43 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Listed all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Prepared all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Started all plugins</p>

<p>Mar 03, 2020 1:50:45 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Augmented all extensions</p>

<p>Mar 03, 2020 1:50:46 PM jenkins.InitReactorRunner$1 onAttained</p>

<p>INFO: Loaded all jobs</p>

<p>Mar 03, 2020 1:50:46 PM hudson.model.AsyncPeriodicWork$1 run</p>

<p>INFO: Started Download metadata</p>

<p>Mar 03, 2020 1:50:46 PM hudson.util.Retrier start</p>

<p>INFO: Attempt #1 to do the action check updates server</p>

<p>Mar 03, 2020 1:50:47 PM jenkins.util.groovy.GroovyHookScript execute</p>

<p>INFO: Executing /var/jenkins_home/init.groovy.d/run.groovy</p>

<p>Mar 03, 2020 1:50:47 PM jenkins.model.Jenkins$5 runTask</p>

<p>WARNING: GroovyInitScript.init failed perhaps due to plugin dependency issues</p>

<p>java.lang.Error: java.lang.reflect.InvocationTargetException</p>

<p> at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)</p>

<p> at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)</p>

<p> at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)</p>

<p> at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)</p>

<p> at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)</p>

<p> at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)</p>

<p> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</p>

<p> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</p>

<p> at java.lang.Thread.run(Thread.java:748)</p>

<p>Caused by: java.lang.reflect.InvocationTargetException</p>

<p> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)</p>

<p> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)</p>

<p> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)</p>

<p> at java.lang.reflect.Method.invoke(Method.java:498)</p>

<p> at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)</p>

<p> ... 8 more</p>
